name: Build and Deploy to ACG-YAO.github.io

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npx vite build

    - name: Set up SSH
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      run: |
      
        # Save private key to a file
        echo "$SSH_DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key

        # Add the key to the ssh-agent
        eval "$(ssh-agent -s)"
        ssh-add deploy_key

        # Ensure ~/.ssh directory exists
        mkdir -p ~/.ssh

        # Add GitHub to the list of known hosts to prevent prompts
        echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==">>~/.ssh/known_hosts

    - name: Deploy to ACG-YAO.github.io using SSH
      run: |
        # Configure Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Clone the deployment repository using SSH
        git clone git@github.com:ACG-YAO/ACG-YAO.github.io.git deploy

        # Copy the built files
        rsync -av --delete dist/ deploy/

        # Commit and push changes
        cd deploy
        git add .
        git commit -m "Deployed using GitHub Actions"
        git push origin master
