name: Build and Deploy to ACG-YAO.github.io

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npx vite build

    - name: Deploy to ACG-YAO.github.io
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        # Configure Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Clone the deployment repository
        git clone https://github.com/ACG-YAO/ACG-YAO.github.io.git deploy

        # Copy the built files
        rsync -av --delete dist/ deploy/

        # Commit and push changes to ACG-YAO.github.io
        cd deploy
        git add .
        git commit -m "Deployed using GitHub Actions"
        git push https://ACG-YAO:${DEPLOY_TOKEN}@github.com/ACG-YAO/ACG-YAO.github.io.git master
